
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.5.1)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DL_DAL.Client
{
	public abstract class _ImpactLevel : SqlClientEntity
	{
		public _ImpactLevel()
		{
			this.QuerySource = "ImpactLevel";
			this.MappingName = "ImpactLevel";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllImpactLevel]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ImpactLevelID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ImpactLevelID, ImpactLevelID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadImpactLevelByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ImpactLevelID
			{
				get
				{
					return new SqlParameter("@ImpactLevelID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter Description
			{
				get
				{
					return new SqlParameter("@Description", SqlDbType.VarChar, 1024);
				}
			}
			
			public static SqlParameter Level
			{
				get
				{
					return new SqlParameter("@Level", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ImpactLevelID = "ImpactLevelID";
            public const string Name = "Name";
            public const string Description = "Description";
            public const string Level = "Level";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ImpactLevelID] = _ImpactLevel.PropertyNames.ImpactLevelID;
					ht[Name] = _ImpactLevel.PropertyNames.Name;
					ht[Description] = _ImpactLevel.PropertyNames.Description;
					ht[Level] = _ImpactLevel.PropertyNames.Level;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ImpactLevelID = "ImpactLevelID";
            public const string Name = "Name";
            public const string Description = "Description";
            public const string Level = "Level";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ImpactLevelID] = _ImpactLevel.ColumnNames.ImpactLevelID;
					ht[Name] = _ImpactLevel.ColumnNames.Name;
					ht[Description] = _ImpactLevel.ColumnNames.Description;
					ht[Level] = _ImpactLevel.ColumnNames.Level;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ImpactLevelID = "s_ImpactLevelID";
            public const string Name = "s_Name";
            public const string Description = "s_Description";
            public const string Level = "s_Level";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ImpactLevelID
	    {
			get
	        {
				return base.Getint(ColumnNames.ImpactLevelID);
			}
			set
	        {
				base.Setint(ColumnNames.ImpactLevelID, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string Description
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description);
			}
			set
	        {
				base.Setstring(ColumnNames.Description, value);
			}
		}

		public virtual int Level
	    {
			get
	        {
				return base.Getint(ColumnNames.Level);
			}
			set
	        {
				base.Setint(ColumnNames.Level, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ImpactLevelID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ImpactLevelID) ? string.Empty : base.GetintAsString(ColumnNames.ImpactLevelID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ImpactLevelID);
				else
					this.ImpactLevelID = base.SetintAsString(ColumnNames.ImpactLevelID, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_Description
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description) ? string.Empty : base.GetstringAsString(ColumnNames.Description);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description);
				else
					this.Description = base.SetstringAsString(ColumnNames.Description, value);
			}
		}

		public virtual string s_Level
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Level) ? string.Empty : base.GetintAsString(ColumnNames.Level);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Level);
				else
					this.Level = base.SetintAsString(ColumnNames.Level, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ImpactLevelID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ImpactLevelID, Parameters.ImpactLevelID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Level
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Level, Parameters.Level);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ImpactLevelID
		    {
				get
		        {
					if(_ImpactLevelID_W == null)
	        	    {
						_ImpactLevelID_W = TearOff.ImpactLevelID;
					}
					return _ImpactLevelID_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public WhereParameter Level
		    {
				get
		        {
					if(_Level_W == null)
	        	    {
						_Level_W = TearOff.Level;
					}
					return _Level_W;
				}
			}

			private WhereParameter _ImpactLevelID_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _Description_W = null;
			private WhereParameter _Level_W = null;

			public void WhereClauseReset()
			{
				_ImpactLevelID_W = null;
				_Name_W = null;
				_Description_W = null;
				_Level_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ImpactLevelID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ImpactLevelID, Parameters.ImpactLevelID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Level
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Level, Parameters.Level);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ImpactLevelID
		    {
				get
		        {
					if(_ImpactLevelID_W == null)
	        	    {
						_ImpactLevelID_W = TearOff.ImpactLevelID;
					}
					return _ImpactLevelID_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public AggregateParameter Level
		    {
				get
		        {
					if(_Level_W == null)
	        	    {
						_Level_W = TearOff.Level;
					}
					return _Level_W;
				}
			}

			private AggregateParameter _ImpactLevelID_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _Description_W = null;
			private AggregateParameter _Level_W = null;

			public void AggregateClauseReset()
			{
				_ImpactLevelID_W = null;
				_Name_W = null;
				_Description_W = null;
				_Level_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertImpactLevel]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ImpactLevelID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateImpactLevel]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteImpactLevel]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ImpactLevelID);
			p.SourceColumn = ColumnNames.ImpactLevelID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ImpactLevelID);
			p.SourceColumn = ColumnNames.ImpactLevelID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description);
			p.SourceColumn = ColumnNames.Description;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Level);
			p.SourceColumn = ColumnNames.Level;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
