
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.5.0)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DL_DAL.Client
{
	public abstract class _UpdateStatusNotificationType : SqlClientEntity
	{
		public _UpdateStatusNotificationType()
		{
			this.QuerySource = "UpdateStatusNotificationType";
			this.MappingName = "UpdateStatusNotificationType";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllUpdateStatusNotificationType]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int UpdateStatusID, int NotificationTypeID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.UpdateStatusID, UpdateStatusID);

parameters.Add(Parameters.NotificationTypeID, NotificationTypeID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadUpdateStatusNotificationTypeByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter UpdateStatusID
			{
				get
				{
					return new SqlParameter("@UpdateStatusID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NotificationTypeID
			{
				get
				{
					return new SqlParameter("@NotificationTypeID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string UpdateStatusID = "UpdateStatusID";
            public const string NotificationTypeID = "NotificationTypeID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[UpdateStatusID] = _UpdateStatusNotificationType.PropertyNames.UpdateStatusID;
					ht[NotificationTypeID] = _UpdateStatusNotificationType.PropertyNames.NotificationTypeID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string UpdateStatusID = "UpdateStatusID";
            public const string NotificationTypeID = "NotificationTypeID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[UpdateStatusID] = _UpdateStatusNotificationType.ColumnNames.UpdateStatusID;
					ht[NotificationTypeID] = _UpdateStatusNotificationType.ColumnNames.NotificationTypeID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string UpdateStatusID = "s_UpdateStatusID";
            public const string NotificationTypeID = "s_NotificationTypeID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int UpdateStatusID
	    {
			get
	        {
				return base.Getint(ColumnNames.UpdateStatusID);
			}
			set
	        {
				base.Setint(ColumnNames.UpdateStatusID, value);
			}
		}

		public virtual int NotificationTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.NotificationTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.NotificationTypeID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_UpdateStatusID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UpdateStatusID) ? string.Empty : base.GetintAsString(ColumnNames.UpdateStatusID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UpdateStatusID);
				else
					this.UpdateStatusID = base.SetintAsString(ColumnNames.UpdateStatusID, value);
			}
		}

		public virtual string s_NotificationTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NotificationTypeID) ? string.Empty : base.GetintAsString(ColumnNames.NotificationTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NotificationTypeID);
				else
					this.NotificationTypeID = base.SetintAsString(ColumnNames.NotificationTypeID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter UpdateStatusID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UpdateStatusID, Parameters.UpdateStatusID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NotificationTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NotificationTypeID, Parameters.NotificationTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter UpdateStatusID
		    {
				get
		        {
					if(_UpdateStatusID_W == null)
	        	    {
						_UpdateStatusID_W = TearOff.UpdateStatusID;
					}
					return _UpdateStatusID_W;
				}
			}

			public WhereParameter NotificationTypeID
		    {
				get
		        {
					if(_NotificationTypeID_W == null)
	        	    {
						_NotificationTypeID_W = TearOff.NotificationTypeID;
					}
					return _NotificationTypeID_W;
				}
			}

			private WhereParameter _UpdateStatusID_W = null;
			private WhereParameter _NotificationTypeID_W = null;

			public void WhereClauseReset()
			{
				_UpdateStatusID_W = null;
				_NotificationTypeID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter UpdateStatusID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UpdateStatusID, Parameters.UpdateStatusID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NotificationTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NotificationTypeID, Parameters.NotificationTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter UpdateStatusID
		    {
				get
		        {
					if(_UpdateStatusID_W == null)
	        	    {
						_UpdateStatusID_W = TearOff.UpdateStatusID;
					}
					return _UpdateStatusID_W;
				}
			}

			public AggregateParameter NotificationTypeID
		    {
				get
		        {
					if(_NotificationTypeID_W == null)
	        	    {
						_NotificationTypeID_W = TearOff.NotificationTypeID;
					}
					return _NotificationTypeID_W;
				}
			}

			private AggregateParameter _UpdateStatusID_W = null;
			private AggregateParameter _NotificationTypeID_W = null;

			public void AggregateClauseReset()
			{
				_UpdateStatusID_W = null;
				_NotificationTypeID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertUpdateStatusNotificationType]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateUpdateStatusNotificationType]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteUpdateStatusNotificationType]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.UpdateStatusID);
			p.SourceColumn = ColumnNames.UpdateStatusID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NotificationTypeID);
			p.SourceColumn = ColumnNames.NotificationTypeID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.UpdateStatusID);
			p.SourceColumn = ColumnNames.UpdateStatusID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NotificationTypeID);
			p.SourceColumn = ColumnNames.NotificationTypeID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
