 BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Project ADD
	OrganizationID int NOT NULL DEFAULT(0)

UPDATE [dbo].[Project]
SET [OrganizationID] = 2

IF NOT EXISTS (SELECT name FROM sysobjects WHERE name = N'FK_Project_Organization')
      ALTER TABLE [dbo].[Project] ADD 
		CONSTRAINT [FK_Project_Organization] FOREIGN KEY ([OrganizationID]) REFERENCES [dbo].[Organization] ([OrganizationID])


COMMIT