
// Generated by MyGeneration Version # (1.1.5.0)

using System;
using System.Data;
using DL_DAL.Client;

namespace DL_WEB.DAL.Client
{
	public class Project : _Project
	{
		public Project()
		{
		
		}

		public DataView LoadProjectByPrimaryKey(int projectID)
		{
			if (projectID > 0)
				this.LoadByPrimaryKey(projectID);
			else
			{
				this.AddNew();
				this.ProjectID = this.ProjectGroupID = this.ProjectStatusID = this.ProjectCategoryID = 0;
                base.Name = base.Description = string.Empty;
			}
			return this.DefaultView;
		}

		public DataView LoadAllProject()
		{
			this.LoadAll();
			return this.DefaultView;
		}

		public DataView LoadAllProjectByOrganizationID(int organizationID)
		{
			base.Where.OrganizationID.Value = organizationID;
			base.Where.OrganizationID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
			base.Query.Load();
			return this.DefaultView;
		}

		public int Update(int projectID, int projectGroupID, string name, string description, DateTime startDate, DateTime finishDate, 
			int projectStatusID, int projectCategoryID, int organizationID)
		{
			this.LoadProjectByPrimaryKey(projectID);

			this.ProjectID = projectID;
		    this.ProjectGroupID = projectGroupID;
		    this.Name = name;
            if (description != null)
		        base.Description = description;
			if (startDate != DateTime.MinValue)
				this.StartDate = startDate;
			if (finishDate != DateTime.MinValue)
				this.FinishDate = finishDate;
		    this.ProjectStatusID = projectStatusID;
		    this.ProjectCategoryID = projectCategoryID;
			base.OrganizationID = organizationID;

			this.Save();

			return this.ProjectID;
		}

        public static string GetProjectName(string orgConnString,
                                            int projectID)
        {
            ProjectView prj = new ProjectView();
            prj.ConnectionString = orgConnString;
            prj.Where.ProjectID.Value = projectID;
            prj.Where.ProjectID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            prj.Query.Load();
            return prj.Name;
        }

        public static DataView GetProjectInfo(string orgConnString,
                                              int projectID)
        {
            ProjectView prj = new ProjectView();
            prj.ConnectionString = orgConnString;
            prj.Where.ProjectID.Value = projectID;
            prj.Where.ProjectID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            prj.Query.Load();
            return prj.DefaultView;
        }

        public static DataView GetProductionUpdates(string orgConnString,
                                                    int projectID)
        {
            ProductionUpdates updates = new ProductionUpdates(orgConnString);
            updates.Where.ProjectID.Value = projectID;
            updates.Where.ProjectID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            updates.Query.AddOrderBy(ProductionUpdates.ColumnNames.BuildDate, MyGeneration.dOOdads.WhereParameter.Dir.DESC);
            updates.Query.Load();
            return updates.DefaultView;
        }

        public static DataView GetProductionLogEntries(string orgConnString,
                                                       int updateID,
                                                       int impactLevelID)
        {
            ProductionLogEntries entries = new ProductionLogEntries(orgConnString);
            entries.Where.UpdateID.Value = updateID;
            entries.Where.UpdateID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            entries.Where.ImpactLevelID.Value = impactLevelID;
            entries.Where.ImpactLevelID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            entries.Query.Load();
            return entries.DefaultView;
        }
	}
}
