
// Generated by MyGeneration Version # (1.1.5.0)

using System;
using System.Data;
using DL_DAL.Client;

namespace DL_WEB.DAL.Client
{
	public class ProjectCategory : _ProjectCategory
	{
		public ProjectCategory()
		{
		
		}

		public DataView LoadAllProjectCategory()
		{
			this.LoadAll();
			return this.DefaultView;
		}
	}
}
