
// Generated by MyGeneration Version # (1.1.5.0)

using System;
using System.Data;
using DL_DAL.Client;

namespace DL_WEB.DAL.Client
{
	public class ProjectGroup : _ProjectGroup
	{
		public ProjectGroup()
		{
		
		}

		public DataView LoadAllProjectGroup()
		{
			base.LoadAll();
			return base.DefaultView;
		}

        public void UpdateProjectGroup(int ID, string Name, string Description)
        {
            base.LoadByPrimaryKey(ID);
            base.Name = Name;
            base.Description = Description;
            base.Save();
        }

        public void Delete(int projectGroupID)
        {
            base.LoadByPrimaryKey(projectGroupID);
            base.MarkAsDeleted();
            base.Save();
        }
	}
}
