
// Generated by MyGeneration Version # (1.1.5.0)

using System;
using DL_DAL.Client;
using System.Data;
using System.Collections.Specialized;

namespace DL_WEB.DAL.Client
{
	public class Update : _Update
	{
		public Update()
		{
		}

		public DataView LoadAllUpdateByProjectID(int projectID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ProjectID, projectID);
			base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllUpdateByProjectID]", parameters);

			return base.DefaultView;
		}

        public override void Save()
        {
            base.Save();
        }
	}
}
