
// Generated by MyGeneration Version # (1.1.5.0)

using System;
using DL_DAL.Master;
using System.Data;

namespace DL_WEB.DAL.Master
{
	public class User : _User
	{
		public User()
        {
            base.ConnectionString = Master.DBConnectionString;
		}

        public static int GetUserID(string Login)
        {
            DL_WEB.DAL.Master.User user = new User();
            user.Where.Login.Value = Login;
            user.Where.Login.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            user.Query.Load();

            return user.UserID;
        }

        public static Guid GetUserGUID(string Login)
        {
            DL_WEB.DAL.Master.User user = new User();
            user.Where.Login.Value = Login;
            user.Where.Login.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            user.Query.Load();

            return user.GUID;
        }

        public DataView LoadAllUser()
        {
            base.LoadAll();
            return base.DefaultView;
        }
	}
}
