
// Generated by MyGeneration Version # (1.1.5.0)

using System;
using System.Data;
using DL_DAL.Master;
using System.Collections;

namespace DL_WEB.DAL.Master
{
    public class UserRole : _UserRole
    {
        #region Constructor

        public UserRole()
        {
            base.ConnectionString = Master.DBConnectionString;
        }

        #endregion

        #region GetUserOrganizations

        public ICollection GetUserOrganizations(int UserID)
        {
            Hashtable oOrgs = new Hashtable();

            Where.UserID.Value = UserID;
            Where.UserID.Operator = MyGeneration.dOOdads.WhereParameter.Operand.Equal;
            Query.Load();

            if (0 == RowCount)
                return oOrgs;

            do
            {
                if (!oOrgs.ContainsKey(OrganizationID))
                {
                    Organization org = new Organization();
                    org.LoadByPrimaryKey(OrganizationID);
                    oOrgs.Add(OrganizationID, org);
                }
            } while (MoveNext());

            return oOrgs;
        }

        #endregion
    }
}
